#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftSide,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightSide,     tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//////////////////////////////////////////////////////////////
//                Teleop Avoid Wierd Code                   //
//////////////////////////////////////////////////////////////

int avoidWeird(int joyval, int noise)
{
/*--------Code to Reduce Noise-----------
       reduces the noise from the
       controller
*/
  if (abs(joyval) < noise)
  {
    joyval = 0;
  }
  return (joyval);
}

int returnValueMotor(int cord, int maxVal)
{
/*-----Code to create value of cord-------
      Creates a function that maps the
      value of cord to a power value for
              the motors

       cord: cordinate value from controller
       returns: a power value for motors
*/
  int velocity = ((maxVal*cord)/127); //Set velocity value based on joystick value
  return velocity;
}

///////////////////////////////////////////////////////////////////////////////////////
//                                                                                   //
//                                  Teleop                                           //
//                                                                                   //
///////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

//***********************************************************//
//                       Variables                           //
//***********************************************************//


//***********************************************************//
//                         Methods                           //
//***********************************************************//

void drive(int ycord,int xcord)
{
  int maxVal = 70;
  int turningVal = returnValueMotor(xcord, maxVal);
  int motorVal = returnValueMotor(ycord, maxVal);

  motor[leftSide] = motorVal + turningVal;

  motor[rightSide] = motorVal - turningVal;
}

//***********************************************************//
//                      User Control                         //
//***********************************************************//

task main()
{
  waitForStart();

  while (true)
  {
    getJoystickSettings(joystick);

    int cont1_left_yval = avoidWeird(joystick.joy1_y1, 20); //y coordinate for the left joystick on controller 1
    int cont1_left_xval = avoidWeird(joystick.joy1_x1, 75); //x coordinate for the left joystick on controller 1

    drive(cont1_left_yval, cont1_left_xval);
  }
}
