#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftSide,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightSide,     tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

//////////////////////////////////////////////////////////////
//                Teleop Avoid Wierd Code                   //
//////////////////////////////////////////////////////////////

int avoidWeird(int joyval, int noise)
{
/*--------Code to Reduce Noise-----------
      reduces the noise from the
      controller
*/
  if (abs(joyval) < noise)
  {
    joyval = 0;
  }
  return (joyval);
}

int returnValueMotor(int cord, int maxVal)
{
/*-----Code to create value of cord-------
      Creates a function that maps the
      value of coordinate to a power value
      for the motors

      cord: cordinate value from controller
      returns: a power value for motors
*/
  int velocity = ((maxVal*cord)/127); //Set velocity value based on joystick value
  return velocity;
}

///////////////////////////////////////////////////////////////////////////////////////
//                                                                                   //
//                                  Teleop                                           //
//                                                                                   //
///////////////////////////////////////////////////////////////////////////////////////

//***********************************************************//
//                       Variables                           //
//***********************************************************//

// Add global variables here as necessary.

//***********************************************************//
//                      Functions                            //
//***********************************************************//

void drive(int ycord,int xcord)
{
	//
	// This function gives the motors power based on the joystick
	// coordinates. It acts on the assumption that all the motors
	// on the left side are in one motor port, and all the motors
	// on the right side are in one motor port.
	//
	// It then creates two values - turningVal and motorVal - based
	// on the joystick x and y coordinates respectively.
	//
	// turningVal and motorVal are added for the left side and
	// subtracted for the right side. This causes the robot to have
	// a full range of turning angles based directly on the graphical
	// position of the joystick.
	//

  int maxVal = 30;
  int turningVal = returnValueMotor(xcord, maxVal);
  int motorVal = returnValueMotor(ycord, maxVal);

  motor[leftSide] = motorVal + turningVal;

  motor[rightSide] = motorVal - turningVal;
}

//***********************************************************//
//                      User Control                         //
//***********************************************************//

task main()
{
  waitForStart();

  while (true)
  {
  	// The call to the include at the beginning of the code to
  	// obtain the positions of the various buttons on the joystick.
    getJoystickSettings(joystick);

    // Buttons on the joystick are assigned to variables. In this case,
    // these variables correspond to the position of the left joystick
    // of controller 1.
    int cont1_left_yval = avoidWeird(joystick.joy1_y1, 20); //y coordinate for the left joystick on controller 1
    int cont1_left_xval = avoidWeird(joystick.joy1_x1, 75); //x coordinate for the left joystick on controller 1

    /* Other Variables */
    //int cont1_right_yval = avoidWeird(joystick.joy1_y2, 20); //y coordinate for the right joystick on controller 1
    //int cont1_right_xval = avoidWeird(joystick.joy1_x2, 20); //x coordinate for the right joystick on controller 1
    //int cont2_left_yval = avoidWeird(joystick.joy2_y1, 35); //y coordinate for the left joystick on controller 2
    //int cont2_left_xval = avoidWeird(joystick.joy2_x1, 35); //x coordinate for the left joystick on controller2
    //int cont2_right_yval = avoidWeird(joystick.joy2_y2, 35); //y coordinate for the right joystick on controller 2
    //int cont2_right_xval = avoidWeird(joystick.joy2_x2, 35); //x coordinate for the right joystick on controller 2
    //int cont2_dPad = joystick.joy2_TopHat; //Value of the dPad for controller 2

    // The call to the function that powers the motors.
    drive(cont1_left_yval, cont1_left_xval);
  }
}
