#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     rightdrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     leftdrive,     tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// NXTDisplayCenteredBigTextLine(line_number, "text")
// NXT buttons - nNxtButtonPressed
//	0 - gray button
//	1 - right button
//	2 - left button
//	3 - orange button

void move_lift(int power)
{
	motor[lift] = power;
}

task main()
{
	int current_power = 15;

	while (true)
	{
		/*if (nNxtButtonPressed == 3)
		{
			eraseDisplay();
			current_power += 5;
			nxtDisplayCenteredBigTextLine(3,"%d", current_power);
		}*/

		if (nNxtButtonPressed == 1)
		{
			move_lift(40);
		}

		else if (nNxtButtonPressed == 2)
		{
			move_lift(-15);
		}

		else
		{
			move_lift(0);
		}
	}

}
