#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     IRSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C2_1,     Hand,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     rightFrontPair, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     leftFrontPair, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     rightRear,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     leftRear,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    Arm,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    Auto_Hand,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	/*
	eraseDisplay();
	string print;
	int n = 0;
	while (n<400){
	print = SensorValue[IRSeeker];
	nxtDisplayCenteredTextLine(0,print);
	wait10Msec(10);
	n = n + 1;
	}
	*/
	return;

}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
void moveStraight(int power, int duration)
{
	motor[rightRear] = -power;
	motor[rightFrontPair]= power;
	motor[leftRear] = power;
	motor[leftFrontPair] = power;
	wait1Msec(duration);
	motor[rightRear] = 0;
	motor[rightFrontPair] = 0;
	motor[leftRear] = 0;
	motor[leftFrontPair] = 0;
}

void move(int powerRight, int powerLeft, int duration)
{
	motor[rightRear] = powerRight;
	motor[rightFrontPair]= powerRight;
	motor[leftRear] = powerLeft;
	motor[leftFrontPair] = powerLeft;
	wait1Msec(duration);
	motor[rightRear] = 0;
	motor[rightFrontPair]= 0;
	motor[leftRear] = 0;
	motor[leftFrontPair] = 0;
}
void hand (int position)
{
	servo[Auto_Hand] = position;
}

void allStop()
{
	motor[rightRear] = 0;
	motor[rightFrontPair]= 0;
	motor[leftRear] = 0;
	motor[leftFrontPair] = 0;
}


task main()
{
	initializeRobot();
	waitForStart(); // Wait for the beginning of autonomous phase.
	bool stop = false;
	int i=0;
	while (!stop)
	{
		if(SensorValue[IRSeeker]==5 )
		{
			if(i<23)
			{
				moveStraight (-50,50);
				hand(60);
				moveStraight (-50,100);
				wait10Msec(50);
				hand(180);
				stop = true;
			}
			else
			{
				hand (60);
				moveStraight (-50,100);
				wait10Msec(50);
				hand(180);
				stop = true;
			}
		}
		else
		{
			moveStraight (-30,100);
		}
		i= i+1;
	}
	//	string temp = i;
	//eraseDisplay();
	//nxtDisplayCenteredBigTextLine( 4,temp);
	//wait10Msec(10000);
	string print;
	print = i;
	nxtDisplayCenteredTextLine(0,print);
	wait10Msec(400);

	int n=0;
	while(26-i > n)
	{
		moveStraight (-30,100);
		n= n+1;
	}
	{
		moveStraight (-50,350);
		move (-50,50,600);
		moveStraight (-50,1700);
		move (-50,50,1500);
		moveStraight (-50,1800);
	}
}
