#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IRSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     Arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Hand,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     Flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     Lift,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    Auto,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

int r;
int z;
void moveStraight(int power, int duration) // Sets up drie commands
{
	motor[Right] = power;
	motor[Left] = power;
	wait1Msec(duration);
	motor[Right] = 0;
	motor[Left] = 0;
}

void move(int powerRight, int powerLeft, int duration) // Sets up drive commands for turning
{
	motor[Right] = powerRight;
	motor[Left] = powerLeft;
	wait1Msec(duration);
	motor[Right] = 0;
	motor[Left] = 0;
}
void hand_1 (int position) //Sets up movement commands for servo
{
	servo[Auto] = position;
}

void allStop()
{
	motor[Right] = 0;
	motor[Left] = 0;
}

//Displays function to set up delay time
int time(){
	int d = 1;
	int wait_time = 0;
	nxtDisplayTextLine(1, "L_ARROW = +time");
	nxtDisplayTextLine(2, "R_ARROW = Determine Position");
	nxtDisplayTextLine(5, "Delay Time?");
	bool select = false;
	while(!select){

		nxtDisplayCenteredTextLine(3, "%d", d);
		if(nNxtButtonPressed == 2){         //Left arrow is button 2
			wait10Msec(50);
			wait_time = 100*d;
			d++;
			select = false;
			}else if(nNxtButtonPressed == 1){    // Right arow is button 1
			wait10Msec(50);
			select = true;
		}
	}
	return wait_time;
}

// Displays Function to Set Up Robot Direction
void position(){
	nxtDisplayTextLine(1, "L_ARROW = ARM FRIST");
	nxtDisplayTextLine(2, "R_ARROW = HAND FIRST");
	nxtDisplayTextLine(5, "WHICH COLOR?");
	bool select = false;
	while(!select){
		if(nNxtButtonPressed == 2){         //Left orange is button 2
			wait10Msec(50);
			r = -1;
			select = true;
			}else if(nNxtButtonPressed == 1){    // Right orange is button 1
			wait10Msec(50);
			r = +1;
			select = true;
		}
	}
	wait10Msec(100);
	eraseDisplay();
	nxtDisplayCenteredBigTextLine(4, "READY!");
}
// Moves to bucket with ir sensor and dumps block
int find_ir(int i){
	bool stops = false;
	while (!stops)
	{
		if(SensorValue[IRSeeker]==5 )
		{
			if(i<23)
			{
				//moveStraight (r*50,50);
				hand_1(60);
				moveStraight (r*50,100);
				wait10Msec(40);
				hand_1(180);
				stops = true;
			}
			// Only needed for last bucket
			else
			{
				hand_1(60);
				//moveStraight (r*50,100);
				wait10Msec(20);
				hand_1(180);
				stops = true;
			}
		}
		else
			moveStraight (r*30,100);
		i= i+1;
	}

	return i;
}
// moves the robot from the bucket to the ramp
void move_past_buckets(int i){
	//	string temp = i;
	//eraseDisplay();
	//nxtDisplayCenteredBigTextLine( 4,temp);
	//wait10Msec(10000);
	string print;
	print = i;
	nxtDisplayCenteredTextLine(0,print);
	wait10Msec(400);

	int n=0;
	while(26-i > n)
	{
		moveStraight (r*30,100);
		n= n+1;
	}
	// Edit this part below to edit movement
	//# in hundreds is rotation time
	// Edit the large number
	{
		moveStraight (r*50,550);
		move (r*50,z*50,800);
		moveStraight (r*50,1300);
		move (r*50,z*50,1000);
		moveStraight (r*50,1900);
	}

}



task main()
{

// Combines all of the sub functions
	int i=0;
	int wait_time;
	disableDiagnosticsDisplay();
	wait_time = time();
	position();
	waitForStart();
	z = r * -1;
	wait10Msec(wait_time);
	i = find_ir(i);
	move_past_buckets(i);
}
