#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IRSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     Flag,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     leftFrontPair, tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    Auto_Hand,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

void moveStraight(int power, int duration)
{
	motor[Right] = power;
	motor[Left] = power;
	wait1Msec(duration);
	motor[Right] = 0;
	motor[Left] = 0;
	motor[leftFrontPair] = 0;
}

void move(int powerRight, int powerLeft, int duration)
{
	motor[Right] = powerRight;
	motor[Left] = powerLeft;
	wait1Msec(duration);
	motor[Right] = 0;
	motor[Left] = 0;
}
void hand (int position)
{
	servo[Auto_Hand] = position;
}

void allStop()
{
	motor[Right] = 0;
	motor[Left] = 0;
}


task main()
{
	initializeRobot();
	waitForStart(); // Wait for the beginning of autonomous phase.
	bool stop = false;
	int i=0;
	while (!stop)
	{
		if(SensorValue[IRSeeker]==5 )
		{
			if(i<23)
			{
				moveStraight (-40,10);
				hand(60);
				moveStraight (-50,100);
				wait10Msec(50);
				hand(180);
				stop = true;
			}
			else
			{
				hand (60);
				moveStraight (-50,100);
				wait10Msec(50);
				hand(180);
				stop = true;
			}
		}
		else
		{
			moveStraight (-30,100);
		}
		i= i+1;
	}

	int n=0;
	while(26-i > n)
	{
		moveStraight (-30,100);
		n= n+1;
	}
	{
		moveStraight (-50,350);
		move (50,-50,600);
		moveStraight (-50,1300);
		move (50,-50,1200);
		moveStraight (-50,2000);
	}
}
