#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     hand,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     leftmotor,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     rightmotor,    tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"
#include "..\includes\AvoidWierd.h"


void drive (int ycord, int xcord,int maxVal)
{
	motor[leftmotor]= returnValueMotor(ycord,maxVal)-(2*returnValueMotor(xcord,maxVal));
	motor[rightmotor]= returnValueMotor(ycord,maxVal)+(2*returnValueMotor(xcord,maxVal));
}

task main()
{
	waitForStart();
	while(true)
	{
		getJoystickSettings(joystick);

		//driving functions
	motor[leftmotor] = joystick.joy1_y1;
	motor[rightmotor] = joystick.joy1_y2;
		int cont1_left_yval = avoidWeird(joystick.joy1_y1,20);
		int cont1_left_xval = avoidWeird(joystick.joy1_x1,75);
		int cont1_right_yval = avoidWeird(joystick.joy1_y2,20);
		int cont1_right_xval = avoidWeird(joystick.joy1_x2,50);
		drive(cont1_left_yval, cont1_left_xval,100);
		drive(cont1_right_yval, cont1_right_xval,60);

		//arm functions
		if(joy1Btn(8)==1)
		{
			motor[arm]=-10;
	  }
	  if(joy1Btn(6)==1)
	  {
	  motor[arm]=80;
	  }
	  if(joy1Btn(6)==0&&joy1Btn(8)==0)
	  {
	  	motor[arm]=0;
	  }

	  //hand functions
	  if(joy1Btn(5)==1)
	  {
	  motor[hand]=15;
	  }
	  if(joy1Btn(7)==1)
	  {
	  motor[hand]=15;
	  }
	  if(joy1Btn(5)&&joy1Btn(7)==0)
	 {
	 motor[hand]=0;
	 }
	}
}
