#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     left,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     wrist,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     arm,           tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "..\includes\AvoidWierd.h"

//***********************************************************//
//                       Variables                           //
//***********************************************************//


//***********************************************************//
//                         Methods                           //
//***********************************************************//

void drive(int ycord,int xcord)
{
  int maxVal = 30;
  int turningVal = returnValueMotor(xcord, maxVal);
  int motorVal = returnValueMotor(ycord, maxVal);

  motor[left] = -motorVal + (2*turningVal);

  motor[right] = -motorVal - (2*turningVal);
}

void shoulderMovement(int ycord)
{
  if (ycord > 0)
  {
    int maxVal = 60;
    motor[arm] = returnValueMotor(ycord, maxVal);
    return;
  }

  else
  {
    int maxVal = 40;
    motor[arm] = returnValueMotor(ycord, maxVal);
    return;
  }
}

void handMovement (int dPad)
{
  if (dPad == 0)
  {
    motor[wrist] = 15;
  }
  if (dPad == 4)
  {
    motor[wrist] = -15;
  }
  if (dPad == 2)
  {
    servo[servo1] = ServoValue[servo1] + 5;
  }
  if (dPad == 6)
  {
    servo[servo1] = ServoValue[servo1] - 5;
  }
  if (dPad == -1)
  {
    motor[wrist] = 0;
  }
}

//***********************************************************//
//                      User Control                         //
//***********************************************************//

task main()
{
  waitForStart();

  servo[servo1] = 128;
  while (true)
  {
    getJoystickSettings(joystick);

    int cont1_left_yval = avoidWeird(joystick.joy1_y1, 20); //y coordinate for the left joystick on controller 1
    int cont1_left_xval = avoidWeird(joystick.joy1_x1, 75); //x coordinate for the left joystick on controller 1
    int cont1_right_yval = avoidWeird(joystick.joy1_y2, 20);
    int cont2_left_yval = avoidWeird(joystick.joy2_y1, 35); //y coordinate for the left joystick on controller 2
    int cont2_right_yval = avoidWeird(joystick.joy2_y2, 35); //y coordinate for the right joystick on controller 2
    int cont2_dPad = joystick.joy2_TopHat; //Value of the dPad for controller 2
  	int cont1_dPad = joystick.joy1_TopHat; //Value of the dPad for controller 1

    drive(cont1_left_yval, cont1_left_xval);
    shoulderMovement(cont1_right_yval);
    handMovement(cont1_dPad);

	}
}
