#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     IRSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     r_lightsensor,  sensorLightActive)
#pragma config(Sensor, S4,     l_lightsensor,  sensorLightActive)
#pragma config(Motor,  mtr_S1_C1_1,     shoulderJoint, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     ramp,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     rightFrontPair, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     leftFrontPair, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     rightRear,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     leftRear,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    handJoint,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//																		Global Variables
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

int black_threshold = 23;
int white_threshold = 37;

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	/*eraseDisplay();
	string print;
	int n = 0;
	while (n<400){
	print = SensorValue[l_lightsensor];
	nxtDisplayCenteredTextLine(0,print);
	wait10Msec(10);
	n = n + 1;
	}
	return;*/

}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
void moveStraight(int power, int duration)
{
	motor[rightRear] = power;
	motor[rightFrontPair]= power;
	motor[leftRear] = power;
	motor[leftFrontPair] = power;
	wait1Msec(duration);
	motor[rightRear] = 0;
	motor[rightFrontPair] = 0;
	motor[leftRear] = 0;
	motor[leftFrontPair] = 0;
}

void move(int powerRight, int powerLeft, int duration)
{
	motor[rightRear] = powerRight;
	motor[rightFrontPair]= powerRight;
	motor[leftRear] = powerLeft;
	motor[leftFrontPair] = powerLeft;
	wait1Msec(duration);
	motor[rightRear] = 0;
	motor[rightFrontPair]= 0;
	motor[leftRear] = 0;
	motor[leftFrontPair] = 0;
}
void movearm (int power, int duration)
{
	motor[shoulderJoint] = power;
	wait1Msec(duration) ;
	motor[shoulderJoint] = 0;
}

void movehand (int position)
{
	servo[handJoint] = position;
}

void pack_hand()
{
	motor[shoulderJoint] = 40;
	wait1Msec(1200);
	servo[handJoint] = 60;
	wait1Msec(350);
	motor[shoulderJoint] = 0;
}

void allStop()
{
	motor[rightRear] = 0;
	motor[rightFrontPair]= 0;
	motor[leftRear] = 0;
	motor[leftFrontPair] = 0;
	motor[shoulderJoint] = 0;
}


task main()
{
	initializeRobot();
	int previousCase = 0;
	int bursts = 0;
	bool isStraight = false;
	waitForStart(); // Wait for the beginning of autonomous phase.
	{
		moveStraight (-50,680);
		move (50,-50,500);

		//Move forward until it the left sensor is not on the grey mat
		while (SensorValue(l_lightsensor) < white_threshold && SensorValue(l_lightsensor) > black_threshold){
			moveStraight(-15,25);
		}

		moveStraight(-50,300);

		while(bursts < 400){

			if (SensorValue(l_lightsensor) > white_threshold && SensorValue(r_lightsensor) < black_threshold){ //left sensor is white and right sensor is black
				moveStraight(-20,10);
				previousCase = 1;
				isStraight = true;
			}
			else if (SensorValue(l_lightsensor) < black_threshold && SensorValue(r_lightsensor) > white_threshold){ //left sensor is black and right sensor is white
				moveStraight(-20,10);
				previousCase = 2;
				isStraight = true;
			}
			else{
				if (previousCase == 1){
					move(-25,25,10);
				}
				else
				{
					move(25,-25,10);
				}
			}

			if (isStraight) {
				bursts += 4;
			}
			else {
				bursts += 1;
			}
			isStraight = false;
		}

		bursts = 0;

		while(bursts < 380){

			if (SensorValue(l_lightsensor) > white_threshold && SensorValue(r_lightsensor) < black_threshold){ //left sensor is white and right sensor is black
				moveStraight(20,10);
				previousCase = 1;
				isStraight = true;
			}
			else if (SensorValue(l_lightsensor) < black_threshold && SensorValue(r_lightsensor) > white_threshold){ //left sensor is black and right sensor is white
				moveStraight(20,10);
				previousCase = 2;
				isStraight = true;
			}
			else{
				if (previousCase == 1){
					move(-20,20,10);
				}
				else
				{
					move(20,-20,10);
				}
			}

			if (isStraight) {
				bursts += 4;
			}

			else {
				bursts += 1;
			}
			isStraight = false;
		}

		movearm (-75,700);
		movehand (160);
		movearm (-75,500);
		movehand (130);

		moveStraight(-20,400);
		movearm(-75,400);
		wait1Msec(200);
		moveStraight(20,400);
		movearm(75,450);

		moveStraight(-20,600);
		movearm(-75,400);
		wait1Msec(200);
		moveStraight(20,600);
		movearm(75,450);

		moveStraight (-20,800);
		movearm (-75,850);
		moveStraight (50,1000);
		pack_hand();

	}
	while (true){
		return;
	}
}
