#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S3,     ,               sensorHiTechnicTouchMux)
#pragma config(Motor,  mtr_S1_C2_1,     shoulderJoint, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     spear,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     rightFrontPair, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     leftFrontPair, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     rightRear,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     leftRear,      tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C1_1,    handJoint,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    irseekerServo,        tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "..\includes\rdpartyrobotcdr-3.3.1\drivers\hitechnic-sensormux.h"
#include "..\includes\rdpartyrobotcdr-3.3.1\drivers\lego-light.h"

#include "..\includes\autoFunctions-rings.h"

// Name the light sensors
const tMUXSensor right_light = msensor_S2_1;
const tMUXSensor middle_light = msensor_S2_2;
const tMUXSensor left_light = msensor_S2_3;

task main(){
	// Set light sensors to active
	LSsetActive(left_light);
	LSsetActive(middle_light);
	LSsetActive(right_light);

	// Set up light sensor variables
	int left_nrm = 0;
	int middle_nrm = 0;
	int right_nrm = 0;

	// Set up temp vals to decrease screen flicker
	int temp_left_nrm = 0;
	int temp_middle_nrm = 0;
	int temp_right_nrm = 0;

	eraseDisplay();
	nxtDisplayCenteredTextLine(1,"LIGHT SENSORS");

	while (true){

		// Read light sensor values
		left_nrm = LSvalNorm(left_light);
		middle_nrm = LSvalNorm(middle_light);
		right_nrm = LSvalNorm(right_light);

		if (temp_left_nrm != left_nrm){
			nxtDisplayCenteredTextLine(3,"L: %d", left_nrm);
			temp_left_nrm = left_nrm;
		}
		if (temp_middle_nrm != middle_nrm){
			nxtDisplayCenteredTextLine(4,"M: %d", middle_nrm);
			temp_middle_nrm = middle_nrm;
		}
		if (temp_right_nrm != right_nrm){
			nxtDisplayCenteredTextLine(5,"R: %d", right_nrm);
			temp_right_nrm = right_nrm;
		}
	}
}
