#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     spear,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     rightdrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     leftdrive,     tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// NXTDisplayCenteredBigTextLine(line_number, "text")
// NXT buttons - nNxtButtonPressed
//	0 - gray button
//	1 - right button
//	2 - left button
//	3 - orange button

void move_spear(int power)
{
	motor[spear] = power;
}

task main()
{
	int current_power = 10;
	string display;
	string tempDisplay;
	nxtDisplayCenteredBigTextLine(1,"Spear");
	nxtDisplayCenteredTextLine(5,"Power: %d", current_power);

	while (true) {

		// If enter button is pressed, add to current power
		/*if (nNxtButtonPressed == kEnterButton){
			current_power += 5;
			nxtDisplayCenteredTextLine(7,"%d", current_power);
		}*/

		if (nNxtButtonPressed == kRightButton){
			move_spear(current_power);
			display = "Moving positive";
		}

		else if (nNxtButtonPressed == kLeftButton){
			move_spear(-current_power);
			display = "Moving negative";
		}

		else{
			move_spear(0);
			display = "Not moving";
		}

		if (display != tempDisplay){
			nxtDisplayCenteredTextLine(4,display);
			tempDisplay = display;
		}
	}

}
