#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightdrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftdrive,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     arm,           tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "..\includes\AvoidWierd.h"

void move_lift(int ycord, int maxVal)
{
	int motorVal = -returnValueMotor(ycord, maxVal);
	motor[lift] = motorVal;
}

void drive(int ycord, int xcord, int maxVal)
{
  int turningVal = -returnValueMotor(xcord, maxVal);
  int motorVal = -returnValueMotor(ycord, maxVal);

  motor[rightdrive] = motorVal - (2*turningVal);
	motor[leftdrive] = motorVal - (2*turningVal);
}

task main()
{

	int max_val_lift = 100;
	int max_val_drive = 50;

 	while (true)
  {
    getJoystickSettings(joystick);

    int cont1_left_yval = avoidWeird(joystick.joy1_y1, 20); //y coordinate for the left joystick on controller 1
    int cont1_right_yval = avoidWeird(joystick.joy1_y2, 20); //y coordinate for the right joystick on controller 1
    int cont1_right_xval = avoidWeird(joystick.joy1_x2, 20); //x coordinate for the right joystick on controller 1

    if (joy1Btn(4) == 1)
    {
    	motor[arm] = 20;
    }
    if (joy1Btn(2) == 1)
    {
    	motor[arm] = -20;
    }
    if (joy1Btn(4) != 1 && joy1Btn(2) != 1)
    {
    	motor[arm] = 0;
    }

    move_lift(cont1_left_yval, max_val_lift);
    drive(cont1_right_yval, cont1_right_xval, max_val_drive);
  }
}
