#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     compass,        sensorI2CHiTechnicCompass)
#pragma config(Sensor, S3,     eopd,           sensorAnalogActive)
#pragma config(Motor,  mtr_S1_C1_1,     shoulderJoint, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     ramp,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     rightFrontPair, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     leftFrontPair, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     rightRear,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     leftRear,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    handJoint,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//																Global Variables
//
// Variables that will be used by the code from outside functions.
//
// Global Variables
//
//		1. name:
//			 description:
//		   function:
//			 use:
//
/////////////////////////////////////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

int nOldHeading = 999;

void initializeRobot()
{
	eraseDisplay();
	int i = 0;
  while (i < 400)
  {
    compassZero = SensorValue[compass];
    if (abs(compassZero - nOldHeading) > 1)
    {
      // Only update when changed to avoid LCD screen flicker
      nxtDisplayCenteredTextLine(0, "%d", compassZero);
      nOldHeading = compassZero;
    }
    i += 1;
  }
  //compassZero = SensorValue[compass];
}

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//													Specific Functions for Gyro
//
// These functions serve the purpose of dealing with the circular nature of the compass sensor values.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////




/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//														Movement Functions
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void moveStraight(int power, int duration)
{
	motor[rightRear] = power;
	motor[rightFrontPair]= power;
	motor[leftRear] = power;
	motor[leftFrontPair] = power;
	wait1Msec(duration);
	motor[rightRear] = 0;
	motor[rightFrontPair] = 0;
	motor[leftRear] = 0;
	motor[leftFrontPair] = 0;
}

void move(int powerRight, int powerLeft, int duration)
{
	motor[rightRear] = powerRight;
	motor[rightFrontPair]= powerRight;
	motor[leftRear] = powerLeft;
	motor[leftFrontPair] = powerLeft;
	wait1Msec(duration);
	motor[rightRear] = 0;
	motor[rightFrontPair]= 0;
	motor[leftRear] = 0;
	motor[leftFrontPair] = 0;
}
void movearm (int power, int duration)
{
	motor[shoulderJoint] = power;
	wait1Msec(duration) ;
	motor[shoulderJoint] = 0;
}

void movehand (int position)
{
	servo[handJoint] = position;
}

void pack_hand()
{
	motor[shoulderJoint] = 40;
	wait1Msec(1600);
	servo[handJoint] = 60;
	wait1Msec(350);
	motor[shoulderJoint] = 0;
}

void allStop()
{
	motor[rightRear] = 0;
	motor[rightFrontPair]= 0;
	motor[leftRear] = 0;
	motor[leftFrontPair] = 0;
	motor[shoulderJoint] = 0;
}

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// This program will utilize the gyro sensor to complete a turn of a specified angle. It will drive forward
// for sometime, turn the correct amount, and stop.
//
// Steps:
//
//		1. Calibrate gyro sensor to initial heading
//
//		2. Drive forward
//				a. Drive forward on the same heading.
//
//		3. Complete a 90 degree turn
//				a.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
	initializeRobot();
	waitForStart(); // Wait for the beginning of autonomous phase.
	wait1Msec(100);

	while (true)
	{
		nxtDisplayCenteredTextLine(0, "%d", SensorValue[compass]);
	}
}
