#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftSide,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightSide,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     shoulderJoint, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     elbowJoint,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    handJoint,            tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

///////////////////////////////////////////////////////////////////////////////////////
//                                                                                   //
//                                  Teleop                                           //
//                                                                                   //
///////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "..\includes\AvoidWierd.h"

//***********************************************************//
//                       Variables                           //
//***********************************************************//

int maxHandValue = 250;
int minHandValue = 20;

//***********************************************************//
//                         Methods                           //
//***********************************************************//

void drive(int ycord,int xcord)
{
  int maxVal = 50;
  int turningVal = returnValueMotor(xcord, maxVal);
  int motorVal = returnValueMotor(ycord, maxVal);

  motor[leftSide] = motorVal + turningVal;

  motor[rightSide] = motorVal - turningVal;
}

void shoulderMovement(int ycord)
{
  if (ycord > 0)
  {
    int maxVal = 40;
    motor[shoulderJoint] = returnValueMotor(ycord, maxVal);
    return;
  }

  else
  {
    int maxVal = 40;
    motor[shoulderJoint] = returnValueMotor(ycord, maxVal);
    return;
  }
}

void handMovement(int dPad)
{
	int currentPosition = ServoValue[handJoint];
	int newPosition = currentPosition;

	if (dPad == 0)
	{
		if ((currentPosition + 1) <= maxHandValue)
		{
			newPosition = currentPosition + 1;
		}
	}
	else if (dPad == 4)
	{
		if ((currentPosition - 1) >= minHandValue)
		{
			newPosition = currentPosition - 1;
		}
	}
	servo[handJoint] = newPosition;
}


//***********************************************************//
//                      User Control                         //
//***********************************************************//

task main()
{
  waitForStart();

  servo[handJoint] = 20;

  while (true)
  {
  	servoChangeRate[handJoint] = 2;
    getJoystickSettings(joystick);

    int cont1_left_yval = avoidWeird(joystick.joy1_y1, 20); //y coordinate for the left joystick on controller 1
    int cont1_left_xval = avoidWeird(joystick.joy1_x1, 75); //x coordinate for the left joystick on controller 1
    int cont1_right_yval = avoidWeird(joystick.joy1_y2, 20); //y coordinate for the right joystick on controller 1
    int cont1_dPad = joystick.joy1_TopHat; //Value of the dPad for controller 2

    /* Other Variables */
    //int cont1_right_xval = avoidWeird(joystick.joy1_x2, 20); //x coordinate for the right joystick on controller 1
    //int cont2_left_yval = avoidWeird(joystick.joy2_y1, 35); //y coordinate for the left joystick on controller 2
    //int cont2_left_xval = avoidWeird(joystick.joy2_x1, 35); //x coordinate for the left joystick on controller2
    //int cont2_right_yval = avoidWeird(joystick.joy2_y2, 35); //y coordinate for the right joystick on controller 2
    //int cont2_right_xval = avoidWeird(joystick.joy2_x2, 35); //x coordinate for the right joystick on controller 2
    //int cont2_dPad = joystick.joy2_TopHat; //Value of the dPad for controller 2

    if (joy1Btn(4) == 1)
    {
    	servoChangeRate[handJoint] = 20;
    	servo[handJoint] = maxHandValue;
    }
    if (joy1Btn(2) == 1)
    {
    	servoChangeRate[handJoint] = 20;
    	servo[handJoint] = minHandValue;
    }

    drive(cont1_left_yval, cont1_left_xval);
    shoulderMovement(cont1_right_yval);
    handMovement(cont1_dPad);
  }
}
