#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Hand,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     Flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    Auto,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

///////////////////////////////////////////////////////////////////////////////////////
//                                                                                   //
//                                  Teleop                                           //
//                                                                                   //
///////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "AvoidWierd.h"

//***********************************************************//
//                      Global Variables                     //
//***********************************************************//

int maxHandValue = 250;
int minHandValue = 20;

//***********************************************************//
//                         Methods                           //
//***********************************************************//
void all_stop()
{
	motor[Left] = 0;
	motor[Right] = 0;
}
void drive(int ycord,int xcord)
{
	int maxVal = 40;
	int turningVal = returnValueMotor(xcord, maxVal);
	int motorVal = returnValueMotor(ycord, maxVal);

	motor[Left] = motorVal - (2*turningVal);

	motor[Right] = motorVal + (2*turningVal);
}

void shoulderMovement(int ycord)
{
	int maxVal = 50;
	motor[Arm] = returnValueMotor(ycord, maxVal);
	return;
}

void handMovement(int ycord)
{
	int maxVal = 50;
	motor[Hand] = returnValueMotor(ycord, maxVal);
	return;
}

void flag_raise(int flag_power)
{
	int maxVal = 50;
	motor[Flag] = returnValueMotor(flag_power, maxVal);
	return;
}

//***********************************************************//
//                      User Control                         //
//***********************************************************//

task main()
{
	waitForStart();

	while (true)
	{
		getJoystickSettings(joystick);
		//driver controls
		int cont1_left_yval = avoidWeird(joystick.joy1_y1, 20); //y coordinate for the left joystick on controller 1
		int cont1_left_xval = avoidWeird(joystick.joy1_x1, 75); //x coordinate for the left joystick on controller 1
		int cont1_right_yval = avoidWeird(joystick.joy1_y2, 20); //y coordinate for the right joystick on controller 1
		//arm/hand controls
		int cont2_right_yval = avoidWeird(joystick.joy2_y2, 20);
		int cont2_left_yval = avoidWeird(joystick.joy2_y1, 20);
		//int cont1_dPad = joystick.joy1_TopHat; //Value of the dPad for controller 2

		drive(cont1_left_yval, cont1_left_xval);
		shoulderMovement(cont2_right_yval);
		handMovement(cont2_left_yval);
		flag_raise(cont1_right_yval);

	}
}
