#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IRSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Lift,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    Auto_Hand,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

int r;
int z;
void moveStraight(int power, int duration)
{
	motor[Right] = power;
	motor[Left] = power;
	wait1Msec(duration);
	motor[Right] = 0;
	motor[Left] = 0;
}

void move(int powerRight, int powerLeft, int duration)
{
	motor[Right] = powerRight;
	motor[Left] = powerLeft;
	wait1Msec(duration);
	motor[Right] = 0;
	motor[Left] = 0;
}
void hand (int position)
{
	servo[Auto_Hand] = position;
}

void allStop()
{
	motor[Right] = 0;
	motor[Left] = 0;
}


int time(){
	int d = 1;
	int wait_time = 0;
	nxtDisplayTextLine(1, "L_ARROW = +time");
	nxtDisplayTextLine(2, "R_ARROW = Determine Position");
	nxtDisplayTextLine(5, "Delay Time?");
	bool select = false;
	while(!select){

		nxtDisplayCenteredTextLine(3, "%d", d);
		if(nNxtButtonPressed == 2){         //Left arrow is button 2
			wait10Msec(50);
			wait_time = 100*d;
			d++;
			select = false;
			}else if(nNxtButtonPressed == 1){    // Right arow is button 1
			wait10Msec(50);
			select = true;
		}
	}
	return wait_time;
}


void position(){
	nxtDisplayTextLine(1, "L_ARROW = FLAG FRIST");
	nxtDisplayTextLine(2, "R_ARROW = ARM FIRST");
	nxtDisplayTextLine(5, "WHICH COLOR?");
	bool select = false;
	while(!select){
		if(nNxtButtonPressed == 2){         //Left orange is button 2
			wait10Msec(50);
			r = -1;
			select = true;
			}else if(nNxtButtonPressed == 1){    // Right orange is button 1
			wait10Msec(50);
			r = +1;
			select = true;
		}
	}
	wait10Msec(100);
	eraseDisplay();
	nxtDisplayCenteredBigTextLine(4, "READY!");
}
int find_ir(int i){
	bool stops = false;
	while (!stops)
	{
		if(SensorValue[IRSeeker]==5 )
		{
			if(i<23)
			{
				moveStraight (r*50,50);
				hand(60);
				moveStraight (r*50,100);
				wait10Msec(40);
				hand(180);
				stops = true;
			}
			else
			{
				hand (60);
				moveStraight (r*50,100);
				wait10Msec(40);
				hand(180);
				stops = true;
			}
		}
		else
			moveStraight (r*30,100);
		i= i+1;
	}

	return i;
}

void move_past_buckets(int i){
	//	string temp = i;
	//eraseDisplay();
	//nxtDisplayCenteredBigTextLine( 4,temp);
	//wait10Msec(10000);
	string print;
	print = i;
	nxtDisplayCenteredTextLine(0,print);
	wait10Msec(400);

	int n=0;
	while(26-i > n)
	{
		moveStraight (r*30,100);
		n= n+1;
	}
	{
		moveStraight (r*50,350);
		move (r*50,z*50,600);
		moveStraight (r*50,1100);
		move (r*50,z*50,700);
		moveStraight (r*50,1900);
	}

}



task main()
{


	int i=0;
	int wait_time;
	disableDiagnosticsDisplay();
	wait_time = time();
	position();
	waitForStart();
	z = r * -1;
	wait10Msec(wait_time);
	i = find_ir(i);
	move_past_buckets(i);
}
